/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\MotionProfiles.h
 *  model: 20-sim_Sensor
 *  expmt: 20-sim_Sensor
 *  date:  April 3, 2017
 *  time:  11:19:58 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.3.7711
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
