/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxsubmod.h
 *  subm:  Sensor_Block
 *  model: 20-sim_Sensor
 *  expmt: 20-sim_Sensor
 *  date:  April 3, 2017
 *  time:  11:19:58 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.3.7711
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_SUBMOD_H
#define XX_SUBMOD_H

/* Our own include files */
#include "xxmodel.h"



/* The submodel functions */
void XXInitializeSubmodel (xx_ModelInstance* model_instance);
void XXCalculateSubmodel (xx_ModelInstance* model_instance, XXDouble t);
void XXTerminateSubmodel (xx_ModelInstance* model_instance, XXDouble t);

#endif

