/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxTable2D.h
 *  model: 20-sim_Sensor
 *  expmt: 20-sim_Sensor
 *  date:  April 3, 2017
 *  time:  11:19:58 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.3.7711
 **********************************************************/

/* This file defines the functions necessary for table 2D lookup
   functions
*/
#ifndef __TABLE2D_H
#define __TABLE2D_H

void Table2D_Initialize ();
void Table2D_Terminate ();

XXInteger Table2D_Table2DInit(XXDouble *inarr, XXInteger inputs, XXDouble *outarr, XXInteger outputs, XXInteger major);
XXInteger Table2D_TableRead(XXDouble *inarr, XXInteger inputs, XXDouble *outarr, XXInteger outputs, XXInteger major);

#endif  /* __TABLE2D_H */

